//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int assignment_id { get; set; }
        public int instructor_course_id { get; set; }
        public string assignment_name { get; set; }
        public string assignment_desc { get; set; }
        public string assignment_type { get; set; }
        public Nullable<int> max_points { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
    }
}
