//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.InstructorCourses = new HashSet<InstructorCours>();
            this.StudentCourses = new HashSet<StudentCours>();
        }
    
        public int course_id { get; set; }
        public int dept_id { get; set; }
        public string course_name { get; set; }
        public string course_desc { get; set; }
        public Nullable<int> num_credits { get; set; }
        public Nullable<int> max_capacity { get; set; }
        public string days_of_week { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public string building { get; set; }
        public Nullable<int> room_no { get; set; }
        public string course_num { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorCours> InstructorCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCours> StudentCourses { get; set; }
        public virtual Department Department { get; set; }
    }

    public class ListCourseViewModel
    {
        public List<Cours> Courses { get; set; }
    }
}
