//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAssignment
    {
        public int assignment_grade_id { get; set; }
        public int assignment_id { get; set; }
        public Nullable<int> student_course_id { get; set; }
        public int student_id { get; set; }
        public Nullable<int> grade { get; set; }
        public Nullable<System.DateTime> submission_date { get; set; }
        public string text_submission { get; set; }
        public string file_submission { get; set; }
        public string instructor_feedback { get; set; }
    }
}
