//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCours
    {
        public int student_course_id { get; set; }
        public int course_id { get; set; }
        public int student_id { get; set; }
        public string letter_grade { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual ulUser ulUser { get; set; }
    }
}
